version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: fastapi_db
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: fastapi_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3309:3306"
    networks:
      - api_network
    volumes:
      - db_data:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  api_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  db_data: